import { FormEvent, useEffect, useMemo, useState } from 'react';
import { DndContext, DragEndEvent, PointerSensor, TouchSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core';
import { SortableContext, arrayMove, rectSortingStrategy, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Download, GripVertical, Heart, LockKeyhole, Medal, RefreshCw, Sparkles, Timer, Trophy, X } from 'lucide-react';

type Submission = { team:string; teamKey:string; attempt:number; order:number[]; exact:number; distance:number; score:number; elapsed:number; createdAt:number };
type Photo = { year:number; src:string };
type Screen = 'home'|'game'|'result'|'ranking'|'admin';

const YEARS=Array.from({length:21},(_,i)=>2006+i);
const ADMIN_PIN='230206';
const STORAGE_KEY='notre-histoire-classement-v2';
const MAX_ATTEMPTS=3;

function shuffle<T>(items:T[]):T[]{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function formatTime(total:number){return `${Math.floor(total/60).toString().padStart(2,'0')}:${(total%60).toString().padStart(2,'0')}`}
function normalizeTeam(value:string){return value.trim().toLocaleLowerCase('fr').replace(/\s+/g,' ')}
function compute(order:number[]){const exact=order.reduce((s,y,i)=>s+(y===YEARS[i]?1:0),0);const distance=order.reduce((s,y,i)=>s+Math.abs(YEARS.indexOf(y)-i),0);return{exact,distance,score:exact}}
function readResults():Submission[]{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function compare(a:Submission,b:Submission){return b.exact-a.exact||a.distance-b.distance||a.elapsed-b.elapsed||a.createdAt-b.createdAt}
function bestResults(items:Submission[]){const map=new Map<string,Submission>();for(const item of items){const current=map.get(item.teamKey);if(!current||compare(item,current)<0)map.set(item.teamKey,item)}return [...map.values()].sort(compare)}
function attemptsFor(items:Submission[],teamKey:string){return items.filter(x=>x.teamKey===teamKey).length}

function SortablePhoto({photo,index}:{photo:Photo;index:number}){const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:photo.year});return <article ref={setNodeRef} className={`photo-card ${isDragging?'dragging':''}`} style={{transform:CSS.Transform.toString(transform),transition}}><span className="position">{index+1}</span><button className="drag-handle" type="button" {...attributes} {...listeners}><GripVertical/></button><img src={photo.src} alt={`Souvenir ${index+1}`} draggable={false}/></article>}

function Ranking({items,onClose}:{items:Submission[];onClose:()=>void}){const sorted=useMemo(()=>bestResults(items),[items]);return <main className="panel-shell"><section className="panel wide"><button className="close" onClick={onClose}><X/></button><Trophy className="big-icon"/><p className="eyebrow">Classement</p><h1>Les meilleurs détectives</h1><p>Meilleure tentative de chaque équipe. Égalité départagée par l’ordre le plus proche, puis par le temps.</p><div className="ranking">{sorted.length===0?<p>Aucune équipe n’a encore terminé.</p>:sorted.map((x,i)=><div className="rank-row" key={x.teamKey}><span>{i<3?['🥇','🥈','🥉'][i]:i+1}</span><strong>{x.team}</strong><span>{x.exact}/21</span><span>{formatTime(x.elapsed)}</span><b>{x.exact} pt{x.exact>1?'s':''}</b></div>)}</div></section></main>}

function Admin({items,onClose}:{items:Submission[];onClose:()=>void}){const[pin,setPin]=useState('');const[open,setOpen]=useState(false);const[detail,setDetail]=useState<Submission|null>(null);const sorted=bestResults(items);const login=(e:FormEvent)=>{e.preventDefault();pin===ADMIN_PIN?setOpen(true):alert('Code PIN incorrect.')};const exportCsv=()=>{const rows=[['Rang','Equipe','Meilleur score','Tentatives','Distance','Temps','Ordre'],...sorted.map((x,i)=>[i+1,x.team,x.exact,attemptsFor(items,x.teamKey),x.distance,formatTime(x.elapsed),x.order.join(' > ')])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='classement-notre-histoire.csv';a.click();URL.revokeObjectURL(url)};if(!open)return <main className="panel-shell"><section className="panel"><button className="close" onClick={onClose}><X/></button><LockKeyhole className="big-icon"/><h1>Espace animateur</h1><form className="start-form" onSubmit={login}><label>Code PIN</label><input type="password" value={pin} onChange={e=>setPin(e.target.value)}/><button type="submit">Accéder</button></form></section></main>;return <main className="panel-shell"><section className="panel wide"><button className="close" onClick={onClose}><X/></button><div className="admin-head"><div><p className="eyebrow">Animateur</p><h1>Résultats</h1><p>Une ligne par équipe, avec sa meilleure tentative sur trois.</p></div><button className="secondary" onClick={exportCsv}><Download/> Export CSV</button></div><div className="ranking">{sorted.map((x,i)=><button className="rank-row clickable" key={x.teamKey} onClick={()=>setDetail(x)}><span>{i+1}</span><strong>{x.team}</strong><span>{x.exact}/21 · {attemptsFor(items,x.teamKey)}/3 essais</span><span>{formatTime(x.elapsed)}</span><b>{x.exact} pt{x.exact>1?'s':''}</b></button>)}</div>{detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><div className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}><X/></button><h2>{detail.team}</h2><p><b>Meilleur score :</b> {detail.exact}/21</p><p><b>Tentatives utilisées :</b> {attemptsFor(items,detail.teamKey)}/3</p><p><b>Écart global :</b> {detail.distance}</p><p><b>Temps :</b> {formatTime(detail.elapsed)}</p><h3>Meilleur ordre proposé</h3><div className="order-list">{detail.order.map((year,i)=><span className={year===YEARS[i]?'correct':''} key={year}>{i+1}. {year}</span>)}</div></div></div>}</section></main>}

export default function App(){
 const initial=YEARS.map(year=>({year,src:`/photos/${year}.jpg`}));
 const[screen,setScreen]=useState<Screen>('home');const[team,setTeam]=useState('');const[photos,setPhotos]=useState<Photo[]>(()=>shuffle(initial));const[elapsed,setElapsed]=useState(0);const[startedAt,setStartedAt]=useState<number|null>(null);const[result,setResult]=useState<Submission|null>(null);const[results,setResults]=useState<Submission[]>(readResults);
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:5}}),useSensor(TouchSensor,{activationConstraint:{delay:120,tolerance:8}}));
 useEffect(()=>{if(screen!=='game'||startedAt===null)return;const tick=()=>setElapsed(Math.floor((Date.now()-startedAt)/1000));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[screen,startedAt]);
 const beginAttempt=(name:string)=>{const key=normalizeTeam(name);const used=attemptsFor(results,key);if(!key)return;if(used>=MAX_ATTEMPTS){alert(`L’équipe « ${name.trim()} » a déjà utilisé ses 3 tentatives.`);return}setTeam(name.trim());setPhotos(shuffle(initial));setElapsed(0);setStartedAt(Date.now());setResult(null);setScreen('game')};
 const start=(e:FormEvent)=>{e.preventDefault();beginAttempt(team)};
 const dragEnd=({active,over}:DragEndEvent)=>{if(!over||active.id===over.id)return;setPhotos(items=>arrayMove(items,items.findIndex(x=>x.year===active.id),items.findIndex(x=>x.year===over.id)))};
 const validate=()=>{if(!confirm('Valider cette tentative ? Elle comptera parmi vos 3 essais.'))return;const order=photos.map(x=>x.year);const teamKey=normalizeTeam(team);const attempt=attemptsFor(results,teamKey)+1;const item:Submission={team:team.trim(),teamKey,attempt,order,elapsed,createdAt:Date.now(),...compute(order)};const next=[item,...results];localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setResults(next);setResult(item);setStartedAt(null);setScreen('result')};
 if(screen==='ranking')return <Ranking items={results} onClose={()=>setScreen(result?'result':'home')}/>;
 if(screen==='admin')return <Admin items={results} onClose={()=>setScreen('home')}/>;
 if(screen==='result'&&result){const remaining=MAX_ATTEMPTS-attemptsFor(results,result.teamKey);return <main className="panel-shell"><section className="panel result"><Medal className="big-icon"/><p className="eyebrow">{result.team} · tentative {result.attempt}/3</p><h1>Votre résultat</h1><div className="score">{result.exact}<small>/21</small></div><div className="result-grid"><div><b>{result.exact}/21</b><span>photos exactement placées</span></div><div><b>{formatTime(result.elapsed)}</b><span>temps réalisé</span></div></div>{remaining>0?<button className="primary" onClick={()=>beginAttempt(result.team)}><RefreshCw/> Retenter ({remaining} essai{remaining>1?'s':''} restant{remaining>1?'s':''})</button>:<p><b>Les 3 tentatives ont été utilisées.</b> Le meilleur résultat est conservé.</p>}<button className="secondary full" onClick={()=>setScreen('ranking')}><Trophy/> Voir le classement</button><button className="secondary full" onClick={()=>{setTeam('');setResult(null);setScreen('home')}}>Nouvelle équipe</button></section></main>}
 if(screen==='home')return <main className="page-shell"><section className="hero-card"><div className="heart-badge"><Heart fill="currentColor"/></div><p className="eyebrow">Laura & Giovanni</p><h1>Notre histoire en 21 photos</h1><div className="divider"/><p className="intro">Depuis 2006, nous écrivons notre plus belle aventure… À vous de la reconstituer !</p><p className="subcopy">Chaque équipe dispose de 3 tentatives. Seul son meilleur résultat compte.</p><form className="start-form" onSubmit={start}><label>Nom ou numéro de la table</label><input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Ex. Table 7 ou Les Siciliens" required/><button type="submit"><Sparkles/> Commencer le jeu</button></form><div className="home-links"><button onClick={()=>setScreen('ranking')}>Classement</button><button onClick={()=>setScreen('admin')}>Espace animateur</button></div></section></main>;
 return <main className="game-shell"><header className="game-header"><div><p className="eyebrow">Équipe : {team} · essai {attemptsFor(results,normalizeTeam(team))+1}/3</p><h2>Remettez les souvenirs dans l’ordre</h2></div><div className="timer"><Timer/> {formatTime(elapsed)}</div></header><p className="hint"><GripVertical/> Maintenez une photo et glissez-la.</p><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}><SortableContext items={photos.map(x=>x.year)} strategy={rectSortingStrategy}><section className="photo-grid">{photos.map((photo,index)=><SortablePhoto key={photo.year} photo={photo} index={index}/>)}</section></SortableContext></DndContext><footer className="action-bar"><button className="secondary" onClick={()=>setPhotos(shuffle(initial))}><RefreshCw/> Mélanger</button><button className="primary" onClick={validate}>Valider l’essai</button></footer></main>
}